package com.smartlibrary.service;

import com.smartlibrary.model.DashboardStats;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class ReportService {
    private final LibraryService libraryService;
    private final UserService userService;

    // Creates a ReportService object with the supplied values.
    // Parameters: libraryService is the helper that manages books and borrowings; userService is the helper that manages user accounts.
    public ReportService(LibraryService libraryService, UserService userService) {
        this.libraryService = libraryService;
        this.userService = userService;
    }

    // Creates a simple PDF report file for the project deliverable.
    // Parameters: output is the file path where the report is written.
    public Path generatePdfLikeReport(Path output) throws IOException {
        DashboardStats stats = libraryService.dashboardStats((int) userService.countActiveUsers(), 0);
        List<String> lines = List.of(
                "Smart Library Management System - Report",
                "Generated: " + LocalDateTime.now(),
                "",
                "Total books: " + stats.totalBooks(),
                "Borrowed books: " + stats.borrowedBooks(),
                "Overdue books: " + stats.overdueBooks(),
                "Active users: " + stats.activeUsers(),
                "Reservations: " + stats.reservations(),
                "",
                "Generated by the JavaFX HCI final project."
        );
        Files.write(output, createSimplePdf(lines));
        return output;
    }

    // Builds the PDF bytes from report text lines.
    // Parameters: lines is the report lines written into the PDF.
    private byte[] createSimplePdf(List<String> lines) {
        StringBuilder stream = new StringBuilder();
        stream.append("BT\n/F1 18 Tf\n72 760 Td\n(Smart Library Management System) Tj\n");
        stream.append("/F1 11 Tf\n0 -28 Td\n");
        for (String line : lines) {
            stream.append("(").append(escapePdf(line)).append(") Tj\n0 -16 Td\n");
        }
        stream.append("ET\n");

        List<String> objects = new ArrayList<>();
        objects.add("1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n");
        objects.add("2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n");
        objects.add("3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>\nendobj\n");
        objects.add("4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n");
        objects.add("5 0 obj\n<< /Length " + stream.length() + " >>\nstream\n" + stream + "endstream\nendobj\n");

        StringBuilder pdf = new StringBuilder("%PDF-1.4\n");
        List<Integer> offsets = new ArrayList<>();
        for (String object : objects) {
            // PDF cross-reference entries need the byte offset of each object.
            offsets.add(pdf.length());
            pdf.append(object);
        }
        int xref = pdf.length();
        pdf.append("xref\n0 ").append(objects.size() + 1).append("\n");
        pdf.append("0000000000 65535 f \n");
        for (Integer offset : offsets) {
            pdf.append(String.format("%010d 00000 n \n", offset));
        }
        pdf.append("trailer\n<< /Size ").append(objects.size() + 1).append(" /Root 1 0 R >>\n");
        pdf.append("startxref\n").append(xref).append("\n%%EOF");
        return pdf.toString().getBytes(StandardCharsets.ISO_8859_1);
    }

    // Escapes text so it can be placed safely inside a PDF stream.
    // Parameters: value is the value to format or store.
    private String escapePdf(String value) {
        return value.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)");
    }
}
